### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mike632t**
Updated version number in README.md

### CODE REVIEW

**Comment by mike632t** [comment]
I forked your code and incorporated my proposed changes to sort out the entry point and display of the month and year.

Not sure if this is the right way to submit those changed to you code though.  The only way to find out seems to be to try it!

**Comment by kevinboone** [comment]
Hi. Thank you for your interest, and for taking time to look into how cpm-cal can be improved. This PR contains a number of changes, some of which I agree are necessary, some (I think) require discussion, and some I'm not all that keen on. 

I certainly want to include the change to the way the header is displayed, and I think the way the entry point is defined needs some consideration. The way I currently do it is to work around a specific problem that another user had, that led to the first segment being padded with '76' bytes. You version works fine for me, but the version I had before the change worked fine for me, as well. I think the problem was in his CPM emulator, but I think there's some scope for thinking about this. 

Some of the changes you've made (e.g., in .gitignore and README.md) seem reasonable, but they seem to be matters of personal preference, rather than functional improvements. Please correct me if I'm wrong about this. I don't object to the changes, but I'm not sure how much they help.

I wouldn't want to change the default week-start day, because I've specifically written cpm-cal to behave -- so far as practicable -- the same as the corresponding Linux utility. There's a reason that CAL.TXT exists, and I wouldn't like it to be deleted. Changing the include filename case in the asm files seems a little odd to me, since your names don't match the case of the actual files, and CP/M doesn't care one way or the other. Perhaps I'm missing something here?

I'm sorry to have what appears to be a heap of complaints. What would suit me better, if you have time, is to have PRs for the specific changes you want to make, so we can discuss them individually. I appreciate your effort, however, and don't like to appear negative.

**Comment by mike632t** [comment]
It wasn't another user - it was me and I don't mind if you want to cherry pick the changes.   

If it helps I think I can submit the changes individually, but I may have to delete my copy and fork your code again (I'm not a git expert).   

- Having the memory filled with HLT instructions may be a bit odd (it is) but to me relying on all the memory being zeroed makes it seem like you enjoy living a bit dangerously...  (Which is probably why I use '-Wall -pedantic -std=gnu99' !). 

- There is nothing like having a standard to make things non-standard!   The reason I changed the code to default to start the week on a Sunday was that on my systems (currently Debian 10 and 11) that **_is_** how 'cal' behaves !   I wonder if that is locale dependent.

- It may depend on the flavour of CP/M but in my experience I have found that filenames on CP/M are actually case sensitive, it is just that normally you don't notice as the CCP turns any user command into uppercase which makes it very difficult to create a file with a lower case filename!   
I'd never noticed this when using MACRO-80 before as I've always used uppercase for everything except labels and comments.  However, if you want to create a file with a lowercase filename on CP/M you can do so by saving a program from MBASIC with lower case letters in the filename.  This of course makes trying to delete it from the command line quite fun to watch.  (Hint - Use KILL "FileName" from MBASIC itself).      
I suspect that it is possible that the CP/M emulator you are using is changing the case of the filename when the BDOS opens a file. (Just to make sure I wasn't misremembering anything I've just confirmed the behaviour above on both CP/M 1.4 and CP/M 2.2 using [simh](https://schorn.ch/altair_4.php)).  

- The changes to .gitignore were simply to limit the number of files that git said were untracked every time I used the git status command, and I updated README.md to keep track of the new version numbers.  Unfortunately I removed the link to the screenshot because it didn't work when I previewed the file (I should have put that back but forgot!). 

I am curious to know if there was any particular reason for using .ASM as the file type rather than .MAC or why you defined all the external functions in a separate .INC files.  I can see that the latter would be very attractive to a 'C' programmer but it seems like a lot of work.  Rather then use the external keyword everywhere I prefer the alternative syntax described on page 3-6 of the manual.  (Though I actually thought the 'C' like organization of your code was pretty cool when I first saw it).

**Comment by kevinboone** [comment]
Using ASEG with /P was a way to avoid having an unspecified block of bytes in the first segment. If I specified an origin in source without ASEG, that's what gave the odd uncommitted bytes. But if that was _your_ problem, and you have a way around it, that's fine with me. The way you've organized things works for me. I'm not sure how you're specifying the start address, however, unless it's a linker default. Maybe I'm just missing something.

I wonder if the Sunday/Monday thing is a locale default, rather than a platform default? In any event, the notion of the week starting on Sunday causes me physical pain ;)

While I take your point about filename case, having case different in a source file from what is on the disk just looks wrong to me. I appreciate that they won't generally look different under CP/M, and I'm not averse to changing all the filenames to upper-case in this repository if that's more CP/M-like. I just don't see a compelling need to.

I'm not fussed about .gitignore -- I'm happy to change it if you think it will help other people.

I used '.asm'/'.inc' for the filenames because that's what I've always done. I have no particular preference.

As you say, though, I'm primarily a C programmer, and so I tend to arrange things in a C-like way.

**Comment by mike632t** [comment]
I've always found it easier to just let the linker do its' thing and just specify the entry point to the program in the END statement. 
e.g:
```
MAIN:	CALL	clinit	; Initialize the command-line parser
	LD	B, 0	; Arg count
  :
  :     Do stuff
  :
rtcse:	DB 0		; sec
	END	MAIN
```
When the linker creates the executable it automatically includes a jump to MAIN: at 0100H, which is why the Data and Program areas (DSEG and CSEG) are automatically set to start at 0103H by default.
```
A:> l80 main,cal/n/e

Data    0103    0907    < 2052>

51733 Bytes Free
[0182   0907        9]
A:> 
```
Note -  If you link using the /X option to produce an Intel HEX file instead, the first address will be 0103H as above but the jump instruction is NOT included in the output!
```
A:> l80 main,cal/n/e/x

Data    0103    0907    < 2052>

51733 Bytes Free
[0182   0907        9]
A:> type cal.hex
:20010300E5215103CD1B0421E602CD1B04E1C9E5217D03CD1B04E1C9D5CD4908B7CA8402E1
:200123007BB7CA8402FE0DD2840232F003D1C9D5CD4908B7CAA802626B22F103D1C9E5CDCB
  :
  :
  :
A:>
```
All sorts of fun can ensue if you don't notice!

**Pull request closed without merging**
